blank_issues_enabled: false
contact_links:
  - name: D3KRISH 
    url: https://github.com/D3KRISH
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/TEAM-D3VIL 
    about: Please report security vulnerabilities here.
